const customErrors = require("../utils/error")


const getAllPurchases = async(req)=>{
    try {
        
    } catch (error) {
        throw (error)
    }
}
const getOnePurchase = async(req)=>{
    try {
        
    } catch (error) {
        throw (error)
    }
}
const createPurchase = async(req)=>{
    try {
        
    } catch (error) {
        throw (error)
    }
}
const deletePurchase = async(req)=>{
    try {
        
    } catch (error) {
        throw (error)
    }
}
const updatePurchase = async(req)=>{
    try {
        
    } catch (error) {
        throw (error)
    }
}


module.exports={
    getAllPurchases,
    getOnePurchase,
    deletePurchase,
    createPurchase,
    updatePurchase
}